### ISSUE TITLE
use a bundle tool or not

### ISSUE THREAD

**Issue by mefengl** [chatgptjs/chatgpt.js#10]
We may use a bundle tool like `esbuild`, then can split this single file into different files and then bundle them into a single file.

The main benefit is that conflict will be much less since working on a different file.

Another benefit is that it can auto-do compatibility work.

**Comment by adamlui** [comment]
Yes that's a good idea if the file grows long

**Comment by mefengl** [comment]
Another may be to let me be able to create and work on a branch except for the main branch. Cause editing branch is much easier than two repos

**Comment by adamlui** [comment]
Ok I added you as team member w/ write access, does that allow you to do what you proposed?

**Comment by mefengl** [comment]
great! thanks
