### ISSUE TITLE
move the add button logic used in wide-screen-mode here?

### ISSUE THREAD

**Issue by mefengl** [chatgptjs/chatgpt.js#16]
such add button to input

add button into the sidebar (like the auto clear history scripts)

**Comment by adamlui** [comment]
Ok I'll do that

**Comment by adamlui** [comment]
Did you like/understand my alias functions routine? Eventually I will make it so that coder can type chatgpt.addButton(label) or chatgpt.addLabelButton etc using similar routine

**Comment by adamlui** [comment]
That way it is truly powerful since very little thinking or reading docs is involved, then ppl can get excited to use it

**Comment by adamlui** [comment]
Because they can type what they think and it just works is the main goal

**Comment by mefengl** [comment]
Yes, I understand that (I also do FP programme too🌚)
Feel free to use any style you prefer. I don't have any particular preferences or opinions about styling (unless it's too ugly)

**Comment by adamlui** [comment]
What's fp programme?

**Comment by mefengl** [comment]
Functional programming

**Comment by adamlui** [comment]
I see, so moving fwd you can add whatever functions you think frontend dev will like, I can change the name to the most common sense English name in direct object definition, then I update aliases which will still allow them to call using variations

**Comment by mefengl** [comment]
I will close this issue cause It was opened by a thief that can't write this himself
