### ISSUE TITLE
current code seems cause infinite loading when run in tampermonkey

### ISSUE THREAD

**Issue by mefengl** [chatgptjs/chatgpt.js#31]
You can move the newest code to https://github.com/chatgptjs/chatgptjs-tampermonkey-starter to find out if it works.

That repo can be a substitute for a test.

**Comment by mefengl** [comment]
One issue could be that the code needs to be shorter for a single ChatGPT prompt. I plan to maintain a shorter version with fewer than 300 lines to address this. This will make it easier to instruct ChatGPT to use this repository for coding purposes.

**Comment by adamlui** [comment]
You can just put the URL I'm @require instead which is how it'seant to be used so should be tested that way

**Comment by adamlui** [comment]
The alias functions generation routine is having problems w/ the non-functional properties, I will fix and put updated code in test repo

**Comment by adamlui** [comment]
@mefengl the synonymizer now does a function check to avoid conflict w/ `isIdle`, `isGenerating`, `status` & `prevStatus` and https://github.com/chatgptjs/chatgpt.js-greasemonkey-test/blob/main/script.js works now

**Comment by adamlui** [comment]
> You can move the newest code to https://github.com/chatgptjs/chatgptjs-tampermonkey-starter to find out if it works.
> 
> That repo can be a substitute for a test.

@mefengl from now on, https://code.chatgptjs.org/chatgpt-latest.min.js will always fetch the latest code from minified release in `chatgpt.js/dist`, so you should use/share that link in all your live scripts

(for testing, https://code.chatgptjs.org/chatgpt-latest.js will fetch the ever-changing `chatgpt.js/chatgpt.js`)
