### ISSUE TITLE
Use of source code without attribution

### ISSUE THREAD

**Issue by adamlui** [chatgptjs/chatgpt.js#34]
@mefengl in your chatgpt-infinite you need to attribute this repo or chatgptjs.org and/or mention copyright me & you under MIT license (and any other scripts you use the code in)

**Comment by adamlui** [comment]
Can you explain why you did not though? (It is stealing if you don't, it's already free)

**Comment by adamlui** [comment]
I will report you to Greasyfork and/or take legal action if you don't remedy this serious matter @mefengl

**Comment by adamlui** [comment]
You have 24 hours @mefengl

**Comment by mefengl** [comment]
? 
Don't worry, I don't mean to remove them, it should be there a few days ago, and it will be there later.

**Comment by adamlui** [comment]
Well since you are not taking this urgently, you have demonstrated you are just a copycat hogging credit for work you did not do. I reported you X3

**Comment by adamlui** [comment]
You copy my menus my fetches my everything you are a leech, pretending to be smart when you use a bot to write your code

**Comment by adamlui** [comment]
That is why your code is so bad you don't even understand basic concepts or structure

**Comment by mefengl** [comment]
I don't know why you are so eager to belittle me. You should know that the code I am currently using is basically functions from chatgpt-utils. 

What you said about it being unreferenced only happened 17 hours ago (because I had AI refactor it).

Also, the reason why I needed to create this repo was that there were issues with the latest code at that time, and I needed a stable repository to use.

I don't want to argue with you because I think a repository like this is good, and there's no need to recreate it.

I only have a little time to do what I want to do. For me, usable code is enough. I like building, not coding.

**Comment by adamlui** [comment]
>  You should know that the code I am currently using is basically functions from chatgpt-utils.

No, you copied my chat-clearing logic and many other functions. Also chatgpt-utils was a copy of my auto-clear and widescreen functions (don't think the world is so stupid, I knew but did not care, any average person can see you are following me to copy)

> What you said about it being unreferenced only happened 17 hours ago (because I had AI refactor it).

It doesn't matter if it happened 1 hour ago, you already said you're not taking care of it now, so I reported you

> Also, the reason why I needed to create this repo was that there were issues with the latest code at that time, and I needed a stable repository to use.

You published it on Greasyfork without the copyright notice, your reason is a lie.

> I don't want to argue with you because I think a repository like this is good, and there's no need to recreate it.

You are trying to recreate it already. I should never let poison into the house

> I only have a little time to do what I want to do. For me, usable code is enough. I like building, not coding.

Do it with other people stop leeching mine (or give credit or else you will find legal trouble)

**Comment by adamlui** [comment]
I am not joking I am in my 30s don't think I am a boy. This may be acceptable in China, but America is the land of lawsuits

**Comment by adamlui** [comment]
...and I have a lot of money to spend pursuing litigation vs. you

**Comment by mefengl** [comment]
`chatgpt-utils was a copy of my auto-clear and widescreen functions`

When I say chatgpt-utils, I mean this https://github.com/mefengl/chatgpt-utils; it's not.

Its code even comes from my very earlier issues

I will reopen that repo, also with other functions that I use

**Comment by mefengl** [comment]
> I am not joking I am in my 30s don't think I am a boy. This may be acceptable in China, but America is the land of lawsuits

It's also not acceptable in China

**Comment by adamlui** [comment]
> I only have a little time

And  I have a lot of time to punish you. I let you in my house to copy/learn for free, and you pay me back by stealing. And you still don't repent or fix, that means you don't care. So I will be taking legal action against you Feng.

> When I say chatgpt-utils, I mean this https://github.com/mefengl/chatgpt-utils; it's not.

> Its code even comes from my very earlier issues

Yes, it is copy. I did textarea DOM manipulation and you copy me few days later. I did chat-clearing and you immediately copy. I use XHR and you copy right away. How can you talk to me like a blind man? Do you seriously believe your own lies? Your behavior is obvious to anyone but yourself, if you are lying to yourself

**Comment by adamlui** [comment]
You are not my first stalker don't think I don't notice, I just don't say anything

**Comment by adamlui** [comment]
...until you stole from me and to this very moment, will not do anything about it. So we are enemies, you made that choice. You choose not to correct your bad ways, so I must punish you now.

**Comment by adamlui** [comment]
The moment you steal credit you are on thin ice. The moment you pretend nothing happened the ice starts melting. Then you say you'll do something "later" = you are falling into the hole now. You choice, not mine.

**Comment by adamlui** [comment]
As I said, I have a lot of time in the world to punish my enemies, so you made a terrible decision to insult my intelligence and dismiss this all and refuse to take action right now this second. You have let me know what you think of me, and I will act accordingly with litigation.

**Comment by adamlui** [comment]
Don't forget we know each other's names, legal action will not be hard

**Comment by mefengl** [comment]
first, I have added it back (not add it, but add it back, basically just after I woke up)

second, do the things you think you should do, let me see how big this mistake is, to use the code I am contributing to

third, I have other jobs to do, bye now

**Comment by adamlui** [comment]
Search for me on LinkedIn (I have lawyers as connecyions)

**Comment by adamlui** [comment]
> first, I have added it back (not add it, but add it back, basically just after I woke up)

I don't know what you add where but the fact you would rather sleep then take me seriously means we are enemies now

> second, do the things you think you should do, let me see how big this mistake is, to use the code I am contributing to

You have contributed nothing but useless functions I was trying to be nice so you can feel like a team mate. The code you used were my advanced functions (I don't care if you use your simple ones)

> third, I have other jobs to do, bye now

You said this before as an excuse you will be inactive, and now I discover the job is stealing. Keep on doing it, you'll see what happens

**Comment by mefengl** [comment]
What I want to say finally is, why do you look at me like that?

**Comment by adamlui** [comment]
> What I want to say finally is, why do you look at me like that?

I have no respect for thieves

**Comment by adamlui** [comment]
You were begging me to add inserting elements because you couldn't figure out how to abstract it from my scripts. Intentionally, I ignored you, knowing you just wanted to steal it for own scripts. (If you knew how you would write it yourself)

**Comment by adamlui** [comment]
I don't care if you copy but when you erase credit you are despicable thief that deserves the full punishment of the law

**Comment by adamlui** [comment]
Only the greediest people think like that. Normal person is happy already for gaining credit for little-to-no work while I do the heavy lifting. But you are too selfish, you went too far...

**Comment by adamlui** [comment]
Also I have many connections with investors and would've let you in if I raised funding for my projects gaining traction. But you have showed your greed is uncontainable, so that is a tragedy

**Comment by adamlui** [comment]
You see my successful traction from very little time spent, so you thought you could copy me. But the difference is I put in hard work and am an expert marketer. You can't just steal what you don't have...

**Comment by adamlui** [comment]
i.e. I made it look easier than it is so you thought you could do it too. Try and find out you made a mistake

**Comment by mefengl** [comment]
You don't understand; I already said before **I don't mean to delete them** (or why I would add them in the first place)

I added it back 17 hours ago because I didn't notice it; I thought it was there

When you calm down, you can think, am I really doing what you say?

**Comment by adamlui** [comment]
> You don't understand; I already said before I don't mean to delete them (or why I would add them in the first place)

Why? Because I told you to look on my LinkedIn and my lawyer connections are scary? And I know your name?

> I didn't add it back 17 hours ago because I didn't notice it; I thought it was there

Show me what tool you used I will test your claim

> When you calm down, you can think, am I really doing what you say?

Not originally, no, you said "later" and pretend nothing was wrong. So you are greedy and disrespectful. I had to pressure you (which I am good at) to make you take action instead of sleep on your butt

**Comment by adamlui** [comment]
Also you did this to 3 different projects, so no, you are lying. (You will find out which ones if GitHub contacts you)

**Comment by adamlui** [comment]
(I reported you for copyright infringement three times for three different repos, you cannot keep claiming 'mistake' it's just not believable, say things that make sense)

**Comment by mefengl** [comment]
I don't know what else to say; I thought some repo you said have "copyright infringement" I may share it with you happily before

I will add the copyright back (if I am not already) when GitHub contacts me

**Comment by adamlui** [comment]
I don't know what you are saying. I am saying my code is all over your projects without proper attribution. You seem to be saying you want to get away with it unless GitHub tells you no. Am I wrong?

**Comment by adamlui** [comment]
(I will also report you on Greasyfork for trying to publish my code as if you are the author)

**Comment by adamlui** [comment]
(You could probably get banned for this)

**Comment by mefengl** [comment]
`saying my code is all over your projects without proper attribution`

Please tell me where; I will add it back if it is.

the `proper attribution` in `chatgpt-playground` I have already added back.

What's else?

**Comment by adamlui** [comment]
I'm not telling you what you know or doing your work for you lol

**Comment by adamlui** [comment]
You are so lazy, even when confronted you want the victim to work for you smh

**Comment by adamlui** [comment]
No wonder you use a bot to write unsurprisingly bad code

**Comment by mefengl** [comment]
Yes, I also use it to write an English sentences, or I can't even talk with you

**Comment by adamlui** [comment]
Why not Google translate

**Comment by mefengl** [comment]
are you calm down?

**Comment by mefengl** [comment]
it's MIT license; of course I will add it.

And I am just using this repo to do other features, what are you worried about?

**Comment by adamlui** [comment]
I don't know what you are saying

**Comment by adamlui** [comment]
You are a co-author of this thanks to my generosity (I really don't need your help, our level is worlds apart I wrote JS since the 1990s) you should be promoting chatgpt.js not yourself using chatgpt.js code. If chatgpt.js goes up you go up, too, how are you so blind to this? Do you not understand I did not begin marketing yet?

**Comment by adamlui** [comment]
With DuckDuckGPT I passed 1k users in just weeks. How do you think that happened? It's not just code I marketed it when ready

**Comment by adamlui** [comment]
You should be using it as a lib and writing something like:

// NOTE: This script uses the powerful chatgpt.js library @ https://chatgptjs.org (c) 2023 Adam Lui & 冯不游.

Then if it gains traction/funding you get money, too...

**Comment by mefengl** [comment]
![image](https://user-images.githubusercontent.com/71683364/227090266-0edc03f9-ecdf-4a15-bdf5-7452975d7f01.png)

I already mentioned it before; I use a copy of chatgptjs because the latest code has a problem (I created an issue for that)

and at that time, the license it here, and then I refactor it to class by ChatGPT, the license it missing at that time

**Comment by adamlui** [comment]
Nope you intentionally published a script under your author account on Greasyfork which serves one purpose: gain exposure for self-authorship. And the chatgpt.js was removed from source code not license

**Comment by mefengl** [comment]
probably you will think why don't you move it to fixed code later,

I will use the same reason, I have other works to do (they pay me, I have to)

**Comment by adamlui** [comment]
Your stories just don't make sense. No one refactoring posts to Greasyfork to gain installs for self- account...

**Comment by adamlui** [comment]
No one paid you to post to Greasyfork, you wanted to boost your install count, how can you pretend it's any other way

**Comment by mefengl** [comment]
I am publish chatgpt-infinite, not chatgptjs

**Comment by adamlui** [comment]
chagpt-infinite removed chagptjs attribution from source code. So you stole my code to boost your personal install count, not what you said earlier (refactoring to contribute to project). Your stories contradict each other

**Comment by adamlui** [comment]
I don't care if you use it but you cannot do it like that, or I will continue to report you. Do you understand?

**Comment by adamlui** [comment]
You are a co-author why are you being so selfish

**Comment by adamlui** [comment]
"Also, the reason why I needed to create this repo was that there were issues with the latest code at that time, and I needed a stable repository to use." Why post on Greasyfork then? Why erase chatgpt.js? You are a co-author that is so crazy, it's like you're stealing the good parts and pullng credit away from the project. How can you be like that? Do your parents know you are this way?

**Comment by mefengl** [comment]
I publish chatgpt-infinite, not chatgptjs, chatgptjs is the library I use, and I do mention it in the source code, except yesterday.

**Comment by adamlui** [comment]
Are you unhappy in life? Do you seek glory using the hard work of others, from those who gave you a chance to be co-author on something great, for no work in return? Why are you so stupid?

**Comment by adamlui** [comment]
> I publish chatgpt-infinite, not chatgptjs, chatgptjs is the library I use, and I do mention it in the source code, except yesterday.

I looked at the history, **not** "except yesterday" but *always* erased. Why do you keep telling me you publish chatgpt-infinite? That is one example where you steal my hard work and erase the credit. What is your point exactly?

**Comment by adamlui** [comment]
Are you saying because you are a contributor to chatgptjs, you can erase any mention of me or it and use my code with impunity?

**Comment by mefengl** [comment]
... what are you talking about, if I don't mention it, tell me where (cause you already know, or I will figure it out later), and I will add it

**Comment by adamlui** [comment]
chatgpt-infinite you erased chatgpt.js and Adam Lui so you can gain installs for appearing impressive for writing everything yourself. Why are you repeating to me you published chatgpt-infinite? Is that a good thing to you?

**Comment by adamlui** [comment]
Can you try to answer the questions I ask instead of changing the subject

**Comment by mefengl** [comment]
`for appearing impressive for writing everything yourself`

no, I don't, the best evidence is that I have added your repo to my GitHub profile.

are you calm down, can you stop being mean to me?

**Comment by adamlui** [comment]
That was a while ago, this chatgpt-infinite idea was just 2 days ago, to erase me so you can get Greasyfork installs. This is a new idea. You finally realized you can just steal the code. But can you answer my question? Why do you keep repeating you published chatgpt-infinite? Is that a good thing to you?

**Comment by mefengl** [comment]
it's funny to me to write this script; I am using chatgptjs as a package,

and I have seem 
![image](https://user-images.githubusercontent.com/71683364/227094658-2e89ab31-ec52-44a4-b096-011ae593b802.png)

I will add it directly in README (if I republish chatgpt-infinite)

**Comment by mefengl** [comment]
You always describe me as a thief who climbs through windows to go to the library and read books, but why would I do that?

**Comment by adamlui** [comment]
Why do you keep lying? You said you published that not the lib to justify it was not stealing. Now you pretend it's "funny" to post my code as your own and erase credit for our own Greasyfork installs.

**Comment by adamlui** [comment]
> You always describe me as a thief who climbs through windows to go to the library and read books, but why would I do that?

People steal code for installs

**Comment by adamlui** [comment]
Just because this is a library doesn't mean you can do that. Do you understand? If not, tell me, why are you allowed to do that?

**Comment by adamlui** [comment]
Even if you think it's legally allowed, why would you do that as co-author of the project (that you don't even have to contribute anything to)?

**Comment by adamlui** [comment]
I really don't understand your reasoning. It's like someone gave you seed that will grow into a money tree, and you eat it because you're hungry

**Comment by adamlui** [comment]
...and the generous stranger is not even expecting you to water the plant

**Comment by adamlui** [comment]
You are just too blind and selfish

**Comment by nukeop** [comment]
Comedy gold

**Comment by adamlui** [comment]
@nukeop I was semi-trolling btw

**Comment by adamlui** [comment]
@jimmystridh I said semi, copyright infrigement is a serious matter so offenders deserve no sympathy and are fair game
