### ISSUE TITLE
chatgpt.alert()

### ISSUE THREAD

**Issue by madkarmaa** [chatgptjs/chatgpt.js#45]
The parameter `btns` in `chatgpt.alert()` doesn't take count of functions that have multiple words (eg. `function hello_world()`) and renders them in the buttons, taken the previous example, as "Hello_world". I think it could be a nice addition.

**Comment by adamlui** [comment]
@madkarmaa actually you can title-case it and it like this:

```js
chatgpt.alert('Title', 'Msg', function thisIsSexyButton() { return })
```

Result:

![image](https://github.com/chatgptjs/chatgpt.js/assets/10906554/880eb615-df80-4001-bafa-9ae9b9ae9b63)

...but I'll add parsing for underscores and hyphens too, thanks for good suggestion

**Comment by madkarmaa** [comment]
yeah, I was just suggesting since some people could use the snake_case instead of the camelCase

**Comment by madkarmaa** [comment]
also, if I may ask, I'm not getting what `renderHTML` does

**Comment by adamlui** [comment]
@madkarmaa it does the same thing as `innerHTML` but without the security risk i.e. convert tags in strings into HTML nodes (but I tested it is not fully working yet, it works with `<div>` and `<span>` and `<a>` but not `<img>` yet)

...so if you supply `<div class="my-class">This is <a href="link">my</a> message</div>` as msg for `chatgpt.alert()`, the msg will display a link, and the sentence will be styled using your custom `my-class`

**Comment by adamlui** [comment]
@madkarmaa I added the `-` and `_` detection, the new jsDelivr URL is `https://cdn.jsdelivr.net/gh/chatgptjs/chatgpt.js@76b0c6869466e1c2200137afc96f9687f7b9616b/dist/chatgpt-1.10.2.min.js`

**Comment by adamlui** [comment]
@madkarmaa for the `renderHTML()` I meant `alert()` uses it before inserting msg, but you can use it too anywhere you would expect to use `innerHTML` (which I learned is unsafe JavaScript practice from studying Google's technical best practices due to cross-site scripting vulnerability)
